-- Run in Snowflake Worksheet as a role with privileges to create warehouse/database/schema/table.

CREATE WAREHOUSE IF NOT EXISTS UNDEAD_ARENA_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS UNDEAD_ARENA_DB;
CREATE SCHEMA IF NOT EXISTS UNDEAD_ARENA_DB.GAME;

USE WAREHOUSE UNDEAD_ARENA_WH;
USE DATABASE UNDEAD_ARENA_DB;
USE SCHEMA GAME;

CREATE TABLE IF NOT EXISTS game_events (
  event_id VARCHAR(36) PRIMARY KEY,
  session_id VARCHAR(36) NOT NULL,
  timestamp TIMESTAMP_NTZ NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  level INTEGER,
  data VARIANT
);

